import { RepoInfo, DocSection } from '../types';

// ─── API Reference Generator ──────────────────────────────────
// Extracts API endpoints from source and presents them in a
// clean, grouped, copy-pasteable reference.

export function generateApiDocs(repo: RepoInfo): DocSection {
  const lines: string[] = [];

  lines.push('# API Reference');
  lines.push('');

  if (repo.apis.length === 0) {
    lines.push('> No API endpoints were automatically detected in this repository.');
    lines.push('');
    lines.push('This could mean:');
    lines.push('- The project doesn\'t expose an HTTP API');
    lines.push('- The API framework isn\'t recognized yet (open an issue!)');
    lines.push('- Routes are dynamically generated');
    lines.push('');
    lines.push('---');
    lines.push(`*Auto-generated by [docforge](https://github.com/martinanatale93/docforge) on ${new Date().toISOString().split('T')[0]}*`);
    return {
      filename: 'api.md',
      title: 'API Reference',
      content: lines.join('\n'),
    };
  }

  lines.push(`> ${repo.apis.length} endpoint${repo.apis.length === 1 ? '' : 's'} detected`);
  lines.push('');

  // Quick summary table
  lines.push('## Summary');
  lines.push('');

  const methodCounts: Record<string, number> = {};
  for (const ep of repo.apis) {
    methodCounts[ep.method] = (methodCounts[ep.method] || 0) + 1;
  }

  lines.push('| Method | Count |');
  lines.push('|--------|-------|');
  for (const [method, count] of Object.entries(methodCounts).sort()) {
    lines.push(`| \`${method}\` | ${count} |`);
  }
  lines.push('');

  // Group by file
  const byFile = new Map<string, typeof repo.apis>();
  for (const ep of repo.apis) {
    const existing = byFile.get(ep.file) || [];
    existing.push(ep);
    byFile.set(ep.file, existing);
  }

  lines.push('## Endpoints');
  lines.push('');

  for (const [file, endpoints] of byFile) {
    lines.push(`### \`${file}\``);
    lines.push('');
    lines.push('| Method | Path | Line | Description |');
    lines.push('|--------|------|------|-------------|');

    for (const ep of endpoints.sort((a, b) => a.line - b.line)) {
      const methodBadge = getMethodBadge(ep.method);
      lines.push(`| ${methodBadge} | \`${ep.path}\` | L${ep.line} | ${ep.description || '—'} |`);
    }
    lines.push('');
  }

  // Endpoint details
  lines.push('## Endpoint Details');
  lines.push('');

  for (const ep of repo.apis) {
    lines.push(`### ${ep.method} \`${ep.path}\``);
    lines.push('');
    lines.push(`- **File:** \`${ep.file}\``);
    lines.push(`- **Line:** ${ep.line}`);
    if (ep.description) {
      lines.push(`- **Description:** ${ep.description}`);
    }
    lines.push('');

    // Example curl
    lines.push('**Example:**');
    lines.push('');
    lines.push('```bash');
    if (ep.method === 'GET') {
      lines.push(`curl http://localhost:3000${ep.path}`);
    } else {
      lines.push(`curl -X ${ep.method} http://localhost:3000${ep.path} \\`);
      lines.push(`  -H "Content-Type: application/json" \\`);
      lines.push(`  -d '{}'`);
    }
    lines.push('```');
    lines.push('');
  }

  lines.push('---');
  lines.push(`*Auto-generated by [docforge](https://github.com/martinanatale93/docforge) on ${new Date().toISOString().split('T')[0]}*`);

  return {
    filename: 'api.md',
    title: 'API Reference',
    content: lines.join('\n'),
  };
}

function getMethodBadge(method: string): string {
  return `**${method}**`;
}
