import { RepoInfo, DocSection } from '../types';

// ─── Architecture Generator ──────────────────────────────────
// Produces a clean architecture overview with tech stack,
// service descriptions, and a Mermaid diagram.

export function generateArchitecture(repo: RepoInfo): DocSection {
  const lines: string[] = [];

  lines.push('# Architecture');
  lines.push('');

  // Tech stack summary
  lines.push('## Tech Stack');
  lines.push('');

  const { languages, frameworks, databases, infrastructure, testing } = repo.techStack;

  if (languages.length) {
    lines.push(`**Languages:** ${languages.join(', ')}`);
    lines.push('');
  }
  if (frameworks.length) {
    lines.push(`**Frameworks:** ${frameworks.join(', ')}`);
    lines.push('');
  }
  if (databases.length) {
    lines.push(`**Data:** ${databases.join(', ')}`);
    lines.push('');
  }
  if (infrastructure.length) {
    lines.push(`**Infrastructure:** ${infrastructure.join(', ')}`);
    lines.push('');
  }
  if (testing.length) {
    lines.push(`**Testing:** ${testing.join(', ')}`);
    lines.push('');
  }

  // Architecture diagram (Mermaid)
  lines.push('## System Diagram');
  lines.push('');
  lines.push('```mermaid');
  lines.push('graph TD');

  const topLevelFolders = repo.folders.filter(f => !f.path.includes('/'));
  const serviceNodes: string[] = [];

  // Generate nodes for key folders
  for (const folder of topLevelFolders) {
    const nodeId = sanitizeNodeId(folder.name);
    const label = `${folder.name}<br/><small>${folder.description}</small>`;
    lines.push(`    ${nodeId}["${folder.name}"]`);
    serviceNodes.push(nodeId);
  }

  // Add relationships if we can infer them
  if (serviceNodes.length > 1) {
    // Connect common patterns
    const hasApi = serviceNodes.find(n => n.match(/api|routes|controllers/i));
    const hasService = serviceNodes.find(n => n.match(/services?/i));
    const hasDb = serviceNodes.find(n => n.match(/db|database|models|entities|repositories/i));
    const hasFrontend = serviceNodes.find(n => n.match(/components|pages|views|frontend|client/i));

    if (hasFrontend && hasApi) {
      lines.push(`    ${hasFrontend} --> ${hasApi}`);
    }
    if (hasApi && hasService) {
      lines.push(`    ${hasApi} --> ${hasService}`);
    }
    if (hasService && hasDb) {
      lines.push(`    ${hasService} --> ${hasDb}`);
    }
    if (hasApi && hasDb && !hasService) {
      lines.push(`    ${hasApi} --> ${hasDb}`);
    }
  }

  lines.push('```');
  lines.push('');

  // Services / modules breakdown
  lines.push('## Modules');
  lines.push('');

  for (const folder of topLevelFolders) {
    lines.push(`### \`${folder.path}/\``);
    lines.push('');
    lines.push(folder.description);
    lines.push('');
    lines.push(`- **Files:** ${folder.fileCount}`);

    // List sub-folders
    const subFolders = repo.folders.filter(f =>
      f.path.startsWith(folder.path + '/') && f.path.split('/').length === 2
    );
    if (subFolders.length > 0) {
      lines.push(`- **Sub-modules:** ${subFolders.map(s => '`' + s.name + '`').join(', ')}`);
    }
    lines.push('');
  }

  // Dependencies overview
  if (repo.packageJson) {
    const depCount = Object.keys(repo.packageJson.dependencies).length;
    const devDepCount = Object.keys(repo.packageJson.devDependencies).length;

    if (depCount > 0 || devDepCount > 0) {
      lines.push('## Dependencies');
      lines.push('');
      lines.push(`- **Production:** ${depCount} packages`);
      lines.push(`- **Development:** ${devDepCount} packages`);
      lines.push('');

      if (depCount > 0) {
        lines.push('### Key Dependencies');
        lines.push('');
        lines.push('| Package | Version |');
        lines.push('|---------|---------|');
        for (const [name, version] of Object.entries(repo.packageJson.dependencies)) {
          lines.push(`| ${name} | ${version} |`);
        }
        lines.push('');
      }
    }
  }

  lines.push('---');
  lines.push(`*Auto-generated by [docforge](https://github.com/martinanatale93/docforge) on ${new Date().toISOString().split('T')[0]}*`);

  return {
    filename: 'architecture.md',
    title: 'Architecture',
    content: lines.join('\n'),
  };
}

function sanitizeNodeId(name: string): string {
  return name.replace(/[^a-zA-Z0-9]/g, '_');
}
