import { RepoInfo, DocSection } from '../types';

// ─── Overview Generator ──────────────────────────────────────
// Produces a clean, human-friendly project overview from README
// and package metadata. This is the "landing page" of the docs.

export function generateOverview(repo: RepoInfo): DocSection {
  const lines: string[] = [];

  lines.push(`# ${formatName(repo.name)}`);
  lines.push('');

  // Description from package.json or first paragraph of README
  const description = repo.packageJson?.description || extractFirstParagraph(repo.readme);
  if (description) {
    lines.push(`> ${description}`);
    lines.push('');
  }

  // Quick facts table
  lines.push('## At a Glance');
  lines.push('');
  lines.push('| | |');
  lines.push('|---|---|');
  if (repo.packageJson?.version) {
    lines.push(`| **Version** | ${repo.packageJson.version} |`);
  }
  if (repo.license) {
    lines.push(`| **License** | ${repo.license} |`);
  }
  if (repo.techStack.languages.length) {
    lines.push(`| **Languages** | ${repo.techStack.languages.join(', ')} |`);
  }
  if (repo.techStack.frameworks.length) {
    lines.push(`| **Frameworks** | ${repo.techStack.frameworks.join(', ')} |`);
  }
  if (repo.techStack.databases.length) {
    lines.push(`| **Databases** | ${repo.techStack.databases.join(', ')} |`);
  }
  lines.push(`| **Files** | ${repo.files.length} |`);
  lines.push(`| **Folders** | ${repo.folders.length} |`);
  if (repo.apis.length) {
    lines.push(`| **API Endpoints** | ${repo.apis.length} |`);
  }
  lines.push(`| **Tests** | ${repo.hasTests ? 'Yes ✓' : 'No ✗'} |`);
  lines.push(`| **CI/CD** | ${repo.hasCI ? 'Yes ✓' : 'No ✗'} |`);
  lines.push(`| **Docker** | ${repo.hasDocker ? 'Yes ✓' : 'No ✗'} |`);
  lines.push('');

  // Getting started from scripts
  if (Object.keys(repo.scripts).length > 0) {
    lines.push('## Quick Start');
    lines.push('');
    lines.push('```bash');
    if (repo.scripts.install) {
      lines.push('npm install');
    }
    if (repo.scripts.dev) {
      lines.push('npm run dev');
    } else if (repo.scripts.start) {
      lines.push('npm start');
    }
    lines.push('```');
    lines.push('');

    lines.push('## Available Scripts');
    lines.push('');
    lines.push('| Command | Description |');
    lines.push('|---------|-------------|');
    for (const [name, cmd] of Object.entries(repo.scripts)) {
      lines.push(`| \`npm run ${name}\` | \`${cmd}\` |`);
    }
    lines.push('');
  }

  // Documentation index
  lines.push('## Documentation');
  lines.push('');
  lines.push('| Document | Description |');
  lines.push('|----------|-------------|');
  lines.push('| [Architecture](architecture.md) | System architecture and tech stack |');
  lines.push('| [API Reference](api.md) | API endpoints and usage |');
  lines.push('| [Project Structure](structure.md) | Folder and file organization |');
  lines.push('');

  lines.push('---');
  lines.push(`*Auto-generated by [docforge](https://github.com/martinanatale93/docforge) on ${new Date().toISOString().split('T')[0]}*`);

  return {
    filename: 'overview.md',
    title: 'Project Overview',
    content: lines.join('\n'),
  };
}

// ─── Helpers ───────────────────────────────────────────────

function formatName(name: string): string {
  return name
    .replace(/[-_]/g, ' ')
    .replace(/\b\w/g, c => c.toUpperCase());
}

function extractFirstParagraph(readme: string | null): string {
  if (!readme) return '';
  // Skip the title line(s) and blank lines, grab first real paragraph
  const lines = readme.split('\n');
  let capturing = false;
  const paragraphLines: string[] = [];

  for (const line of lines) {
    const trimmed = line.trim();
    if (!capturing) {
      // Skip headings and blank lines
      if (trimmed.startsWith('#') || trimmed === '') continue;
      capturing = true;
    }
    if (capturing) {
      if (trimmed === '' && paragraphLines.length > 0) break;
      paragraphLines.push(trimmed);
    }
  }

  return paragraphLines.join(' ').slice(0, 300);
}
