import { RepoInfo, DocSection } from '../types';

// ─── Structure Generator ──────────────────────────────────────
// Produces a visual, annotated project structure that explains
// every folder and key file.

export function generateStructure(repo: RepoInfo): DocSection {
  const lines: string[] = [];

  lines.push('# Project Structure');
  lines.push('');
  lines.push(`> ${repo.folders.length} directories, ${repo.files.length} files`);
  lines.push('');

  // Build tree
  lines.push('## Directory Tree');
  lines.push('');
  lines.push('```');
  lines.push(`${repo.name}/`);

  // Build a tree from top-level folders
  const topLevel = repo.folders.filter(f => !f.path.includes('/'));
  const nested = repo.folders.filter(f => f.path.includes('/'));
  const topLevelFiles = repo.files.filter(f => !f.path.includes('/'));

  for (let i = 0; i < topLevel.length; i++) {
    const folder = topLevel[i];
    const isLast = i === topLevel.length - 1 && topLevelFiles.length === 0;
    const prefix = isLast ? '└── ' : '├── ';
    const childPrefix = isLast ? '    ' : '│   ';

    lines.push(`${prefix}${folder.name}/`);

    // Find immediate children of this folder
    const children = nested.filter(f => {
      const parts = f.path.split('/');
      return parts.length === 2 && parts[0] === folder.name;
    });

    for (let j = 0; j < children.length; j++) {
      const child = children[j];
      const childIsLast = j === children.length - 1;
      const childPre = childIsLast ? '└── ' : '├── ';
      lines.push(`${childPrefix}${childPre}${child.name}/`);
    }
  }

  // Top-level files
  for (let i = 0; i < topLevelFiles.length; i++) {
    const file = topLevelFiles[i];
    const isLast = i === topLevelFiles.length - 1;
    const prefix = isLast ? '└── ' : '├── ';
    lines.push(`${prefix}${file.name}`);
  }

  lines.push('```');
  lines.push('');

  // Folder explanations
  lines.push('## Directory Guide');
  lines.push('');
  lines.push('| Directory | Purpose | Files |');
  lines.push('|-----------|---------|-------|');

  for (const folder of repo.folders) {
    lines.push(`| \`${folder.path}/\` | ${folder.description} | ${folder.fileCount} |`);
  }
  lines.push('');

  // Key files
  lines.push('## Key Files');
  lines.push('');

  const keyFiles = repo.files.filter(f => isKeyFile(f.name));
  if (keyFiles.length > 0) {
    lines.push('| File | Purpose |');
    lines.push('|------|---------|');
    for (const file of keyFiles) {
      lines.push(`| \`${file.path}\` | ${describeFile(file.name)} |`);
    }
    lines.push('');
  }

  // File type breakdown
  lines.push('## File Types');
  lines.push('');

  const extCounts: Record<string, number> = {};
  for (const file of repo.files) {
    const ext = file.extension || '(no extension)';
    extCounts[ext] = (extCounts[ext] || 0) + 1;
  }

  const sorted = Object.entries(extCounts).sort((a, b) => b[1] - a[1]);
  lines.push('| Extension | Count | Percentage |');
  lines.push('|-----------|-------|------------|');
  for (const [ext, count] of sorted.slice(0, 15)) {
    const pct = ((count / repo.files.length) * 100).toFixed(1);
    lines.push(`| \`${ext}\` | ${count} | ${pct}% |`);
  }
  lines.push('');

  // Code comment coverage
  const sourceFiles = repo.files.filter(f =>
    ['.ts', '.js', '.tsx', '.jsx', '.py', '.cs', '.java', '.go', '.rb'].includes(f.extension)
  );
  if (sourceFiles.length > 0) {
    const commented = sourceFiles.filter(f => f.hasComments).length;
    const pct = ((commented / sourceFiles.length) * 100).toFixed(0);
    lines.push('## Code Comment Coverage');
    lines.push('');
    lines.push(`**${pct}%** of source files contain comments (${commented}/${sourceFiles.length})`);
    lines.push('');
    lines.push(generateProgressBar(commented / sourceFiles.length));
    lines.push('');
  }

  lines.push('---');
  lines.push(`*Auto-generated by [docforge](https://github.com/martinanatale93/docforge) on ${new Date().toISOString().split('T')[0]}*`);

  return {
    filename: 'structure.md',
    title: 'Project Structure',
    content: lines.join('\n'),
  };
}

// ─── Helpers ───────────────────────────────────────────────

function isKeyFile(name: string): boolean {
  const keyNames = [
    'package.json', 'tsconfig.json', 'Dockerfile', 'docker-compose.yml',
    'docker-compose.yaml', '.env.example', 'Makefile', 'README.md',
    'jest.config.ts', 'jest.config.js', 'vitest.config.ts',
    '.eslintrc.js', '.eslintrc.json', '.prettierrc',
    'next.config.js', 'next.config.mjs', 'vite.config.ts',
    'webpack.config.js', 'rollup.config.js',
    'serverless.yml', 'cdk.json', 'terraform.tf',
    'Procfile', 'vercel.json', 'netlify.toml',
    'LICENSE', 'CHANGELOG.md', 'CONTRIBUTING.md',
  ];
  return keyNames.includes(name);
}

function describeFile(name: string): string {
  const descriptions: Record<string, string> = {
    'package.json': 'Node.js project manifest and dependencies',
    'tsconfig.json': 'TypeScript compiler configuration',
    'Dockerfile': 'Container image definition',
    'docker-compose.yml': 'Multi-container orchestration',
    'docker-compose.yaml': 'Multi-container orchestration',
    '.env.example': 'Environment variable template',
    'Makefile': 'Build automation commands',
    'README.md': 'Project documentation entry point',
    'jest.config.ts': 'Jest test framework configuration',
    'jest.config.js': 'Jest test framework configuration',
    'vitest.config.ts': 'Vitest test framework configuration',
    '.eslintrc.js': 'ESLint linting rules',
    '.eslintrc.json': 'ESLint linting rules',
    '.prettierrc': 'Prettier code formatting rules',
    'next.config.js': 'Next.js framework configuration',
    'next.config.mjs': 'Next.js framework configuration',
    'vite.config.ts': 'Vite build tool configuration',
    'webpack.config.js': 'Webpack bundler configuration',
    'rollup.config.js': 'Rollup bundler configuration',
    'serverless.yml': 'Serverless Framework deployment config',
    'cdk.json': 'AWS CDK infrastructure config',
    'Procfile': 'Process manager / Heroku config',
    'vercel.json': 'Vercel deployment config',
    'netlify.toml': 'Netlify deployment config',
    'LICENSE': 'Project license',
    'CHANGELOG.md': 'Version history and changes',
    'CONTRIBUTING.md': 'Contribution guidelines',
  };
  return descriptions[name] || 'Project file';
}

function generateProgressBar(ratio: number): string {
  const filled = Math.round(ratio * 20);
  const empty = 20 - filled;
  return `${'█'.repeat(filled)}${'░'.repeat(empty)} ${(ratio * 100).toFixed(0)}%`;
}
